/**
 * Words every OpenTabletop app uses for the same things (terrains, roads and rivers,
 * seasons, moon phases, the concepts of maps and trips), written once: each app's and
 * package's dictionary refers to these instead of copying them. Pack content (a system's
 * own names) never goes here.
 */
export const vocabulary = {
  en: {
    terms: {
      terrain: 'Terrain',
      terrains: 'Terrains',
      region: 'Region',
      regions: 'Regions',
      tags: 'Tags',
      season: 'Season',
      weather: 'Weather',
      fatigue: 'Fatigue',
      supplies: 'Supplies',
    },
    seasons: { spring: 'spring', summer: 'summer', autumn: 'autumn', winter: 'winter' },
    moonPhases: { new: 'new', waxing: 'waxing', full: 'full', waning: 'waning' },
    /** The kinds of definition that can be rolled. */
    kinds: { table: 'Table', oracle: 'Oracle', generator: 'Generator', deck: 'Deck' },
    pathKinds: {
      road: 'Road',
      trail: 'Trail',
      river: 'River',
      wall: 'Wall',
      border: 'Border',
    },
    terrains: {
      steppe: 'Steppe',
      plains: 'Plains',
      forest: 'Forest',
      hills: 'Hills',
      mountains: 'Mountains',
      badlands: 'Badlands',
      desert: 'Desert',
      swamp: 'Swamp',
      lake: 'Lake',
      sea: 'Sea',
      snow: 'Snow',
      farmland: 'Farmland',
      jungle: 'Jungle',
      taiga: 'Taiga',
      tundra: 'Tundra',
      volcanic: 'Volcanic',
      heath: 'Heath',
      savanna: 'Savanna',
      'dense-forest': 'Dense forest',
      marsh: 'Marsh',
      peaks: 'Peaks',
      canyon: 'Canyon',
      oasis: 'Oasis',
      glacier: 'Glacier',
      coast: 'Coast',
      'deep-sea': 'Deep sea',
      city: 'City',
      suburbs: 'Suburbs',
      industrial: 'Industrial',
      ruins: 'Ruins',
      wasteland: 'Wasteland',
      irradiated: 'Irradiated',
      'toxic-swamp': 'Toxic swamp',
      crater: 'Crater',
      'alien-jungle': 'Alien jungle',
      'crystal-field': 'Crystal field',
      'lava-field': 'Lava field',
      regolith: 'Regolith',
      space: 'Space',
      nebula: 'Nebula',
      'asteroid-field': 'Asteroid field',
    },
  },
  es: {
    terms: {
      terrain: 'Terreno',
      terrains: 'Terrenos',
      region: 'Región',
      regions: 'Regiones',
      tags: 'Etiquetas',
      season: 'Estación',
      weather: 'Clima',
      fatigue: 'Fatiga',
      supplies: 'Provisiones',
    },
    seasons: { spring: 'primavera', summer: 'verano', autumn: 'otoño', winter: 'invierno' },
    moonPhases: { new: 'nueva', waxing: 'creciente', full: 'llena', waning: 'menguante' },
    kinds: { table: 'Tabla', oracle: 'Oráculo', generator: 'Generador', deck: 'Mazo' },
    pathKinds: {
      road: 'Camino',
      trail: 'Sendero',
      river: 'Río',
      wall: 'Muro',
      border: 'Frontera',
    },
    terrains: {
      steppe: 'Estepa',
      plains: 'Llanura',
      forest: 'Bosque',
      hills: 'Colinas',
      mountains: 'Montañas',
      badlands: 'Tierras baldías',
      desert: 'Desierto',
      swamp: 'Pantano',
      lake: 'Lago',
      sea: 'Mar',
      snow: 'Nieve',
      farmland: 'Cultivos',
      jungle: 'Jungla',
      taiga: 'Taiga',
      tundra: 'Tundra',
      volcanic: 'Volcánico',
      heath: 'Brezal',
      savanna: 'Sabana',
      'dense-forest': 'Bosque denso',
      marsh: 'Marisma',
      peaks: 'Cumbres',
      canyon: 'Cañón',
      oasis: 'Oasis',
      glacier: 'Glaciar',
      coast: 'Costa',
      'deep-sea': 'Mar profundo',
      city: 'Ciudad',
      suburbs: 'Afueras',
      industrial: 'Industrial',
      ruins: 'Ruinas',
      wasteland: 'Páramo',
      irradiated: 'Irradiado',
      'toxic-swamp': 'Ciénaga tóxica',
      crater: 'Cráter',
      'alien-jungle': 'Jungla alienígena',
      'crystal-field': 'Campo de cristales',
      'lava-field': 'Campo de lava',
      regolith: 'Regolito',
      space: 'Espacio',
      nebula: 'Nebulosa',
      'asteroid-field': 'Campo de asteroides',
    },
  },
} as const
